In [11]:
from data_handling import joint_iterator_from_file
it = joint_iterator_from_file("data/train", time_major=False)

In [12]:
import numpy as np

X, Y, _, _, _ = it.next(10)
shape = Y.shape
np.random.seed(1)
noise = np.random.binomial(1, 0.1, shape)
Y_noise = Y + noise

print(shape)


(10, 10)


In [28]:
from difflib import SequenceMatcher


def evaluate(A, B, end_code=2):
    assert A.shape == B.shape
    
    n_examples = 0
    correct_examples = 0
    similarity_scores = []
    
    zipped = zip(A, B)
    for a_raw, b_raw in zipped:
        a = clean_end(a_raw, end_code)
        b = clean_end(b_raw, end_code)

        
        n_examples += 1
        sm = SequenceMatcher(a=a, b=b)
        similarity = sm.ratio()
        similarity_scores.append(similarity)
        if similarity == 1:
            correct_examples += 1
            
        print(a)
        print(b)
        print(similarity)
        print()
        
def clean_end(a, token):
    try:
        idx = list(a).index(token)
        return a[:idx]
    except ValueError:
        return list(a)

evaluate(Y, Y_noise)

[1, 44, 69, 12, 28, 17, 43, 70, 55, 51]
[1, 44, 69, 12, 28, 17, 43, 70, 55, 51]
1.0

[ 1 45 37 72 12 56]
[ 1 45 37 72 12 56]
1.0

[ 1 69 48 82 36 27 63 72 70]
[ 1 70 48 82 36 27 63 72 70]
0.8888888888888888

[ 1 47 55 70 68 56 41 58]
[ 1 47 56 70 68 56 41 58]
0.875

[ 1 27 69 41 85 12 58 12 70]
[]
0.0

[ 1 49 58 72 69 80 29 36 85]
[ 1 49 58 72 69 80 29 36 85]
1.0

[ 1 71 33 68 51]
[ 1 71 33 68 51]
1.0

[ 1 55 13 29 58 36]
[]
0.0

[1, 55, 4, 56, 12, 55, 41, 71, 12, 58]
[1, 55, 4, 56, 12, 55, 41, 72, 12, 58]
0.9

[ 1 44 21 28 61 85]
[1, 45, 21, 28, 61, 85, 3, 0, 0, 0]
0.625

